---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g ember-cli
  - npm install -g bower
  - npm install -g phantomjs-prebuilt

install:
  - cd cern-webrtc-client
  - npm install
  - bower install

script:
  - ember test